global:
  resolve_timeout: 5m

route:
  group_by: [Alertname]
  # group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  # Send all notifications to me.
  receiver: email-me
receivers:
- name: email-me
  email_configs:
  - send_resolved: true
    to: devops@blick.ng
    from: devops@blick.ng
    smarthost: blick.ng:587
    auth_username: "devops@blick.ng"
    auth_identity: "devops@blick.ng"
    auth_password: "****"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']